using App.Application.Interfaces;
using App.Application.Interfaces.Core;
using App.Core.Entities.Core;
using App.Infrastructure.Database;
using Dapper;

namespace App.Infrastructure.Repository.Core
{
    public class SesionUsuarioEvidenciaRepository : ISesionUsuarioEvidenciaRepository
    {
        private readonly IDbConnectionFactory _dbFactory;
        private readonly IFileStorageService _fileStorage;

        public SesionUsuarioEvidenciaRepository(IDbConnectionFactory dbFactory, IFileStorageService fileStorage)
        {
            _dbFactory = dbFactory;
            _fileStorage = fileStorage;
        }

        public async Task<Guid> AddAsync(Guid createdBy, Guid sesionUsuarioId, Stream content, string originalFileName, CancellationToken cancellationToken = default)
        {
            // Save file to storage
            var relativePath = await _fileStorage.SaveAsync(content, originalFileName, "SesionUsuarioEvidencia", cancellationToken);

            // Create DB record. id is generated by the database (RETURNING id)
            const string query = "INSERT INTO sesion_usuario_evidencia (sesion_usuario_id, ruta_foto, created_at, created_by) VALUES (@sesion_usuario_id, @ruta_foto, @created_at, @created_by) RETURNING id";

            var p = new DynamicParameters();
            p.Add("@sesion_usuario_id", sesionUsuarioId);
            p.Add("@ruta_foto", relativePath);
            p.Add("@created_at", DateTimeOffset.UtcNow);
            p.Add("@created_by", createdBy);

            using (var connection = _dbFactory.CreateConnection())
            {
                connection.Open();
                using var tx = connection.BeginTransaction();
                try
                {
                    var id = await connection.ExecuteScalarAsync<Guid>(query, p, tx);
                    tx.Commit();
                    return id;
                }
                catch
                {
                    try { tx.Rollback(); } catch { }
                    throw;
                }
            }
        }

        public async Task DeleteAsync(Guid id)
        {
            const string sql = "UPDATE sesion_usuario_evidencia SET deleted_at = now() WHERE id = @id";
            var p = new DynamicParameters();
            p.Add("@id", id);

            using (var connection = _dbFactory.CreateConnection())
            {
                connection.Open();
                await connection.ExecuteAsync(sql, p);
            }
        }

        public async Task<IReadOnlyList<SesionUsuarioEvidencia>> GetAllAsync(Guid sesionUsuarioId)
        {
            const string sql = "SELECT * FROM sesion_usuario_evidencia WHERE sesion_usuario_id = @sesionUsuarioId AND deleted_at IS NULL ORDER BY created_at";
            var p = new DynamicParameters();
            p.Add("@sesionUsuarioId", sesionUsuarioId);

            using (var connection = _dbFactory.CreateConnection())
            {
                connection.Open();
                var items = await connection.QueryAsync<SesionUsuarioEvidencia>(sql, p);
                return items.AsList();
            }
        }

        public async Task<Guid> GetByIdAsync(Guid id)
        {
            const string sql = "SELECT * FROM sesion_usuario_evidencia WHERE id = @id AND deleted_at IS NULL";
            var p = new DynamicParameters();
            p.Add("@id", id);

            using (var connection = _dbFactory.CreateConnection())
            {
                connection.Open();
                var item = await connection.QueryFirstOrDefaultAsync<SesionUsuarioEvidencia>(sql, p);
                return item != null ? item.id : Guid.Empty;
            }
        }
    }
}
